---
# Source: filebeat/templates/clusterrole.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: c-logging-filebeat
  labels:
    app.kubernetes.io/name: filebeat
    helm.sh/chart: filebeat-4.0.0
    app.kubernetes.io/instance: c-logging-filebeat
    app.kubernetes.io/managed-by: Helm
rules:
- apiGroups: [""]
  resources:
  - namespaces
  - pods
  - nodes
  verbs: ["get", "list", "watch"]
