---
#

apiVersion: v1
kind: ServiceAccount
metadata:
  name: c-logging-kibana
  namespace: c-logging
  labels:
    k8s-app: c-logging-kibana
# imagePullSecrets:
#   - name: {{ cCatalogBaseimagePullSecret }} 