---
apiVersion: beat.k8s.elastic.co/v1beta1
kind: Beat
metadata:
  name: c-logging-filebeat
  namespace: c-logging
  labels:
    app.kubernetes.io/name: filebeat
    app.kubernetes.io/instance: c-logging-filebeat
    k8s-app: c-logging-filebeat
    app.kubernetes.io/managed-by: iscp
    app.kubernetes.io/app-name: c-logging
    app.kubernetes.io/app-catalog: simple
    app.kubernetes.io/app-sla: 24x7
    app.kubernetes.io/app-management: commontools
    app.kubernetes.io/component: filebeat
    app.kubernetes.io/version: 8.17.0
spec:
  type: filebeat
  version: 8.17.0
  image: "{{ imageInstanceLocation }}/{{ filebeatImageName }}:{{ filebeatImageTag }}"
  elasticsearchRef:
    name: c-logging-elasticsearch
  kibanaRef:
    name: c-logging-kibana
  config:
    # Internal Metrics: https://www.elastic.co/guide/en/beats/filebeat/master/http-endpoint.html
    http:
      enabled: true
      host: localhost
      port: 5066
    # https://www.elastic.co/guide/en/beats/filebeat/current/configuration-logging.html
    logging:
      metrics.enabled: false
      level: info
    # https://www.elastic.co/guide/en/beats/filebeat/7.9/configuration-monitor.html
    # https://www.elastic.co/guide/en/beats/filebeat/current/monitoring-internal-collection.html
    monitoring:
      enabled: false
    filebeat:
      # Section modules
      # https://www.elastic.co/guide/en/beats/filebeat/current/filebeat-module-system.html
      # Add modules configuration
      inputs:
        - type: container
          paths:
            - /var/log/containers/*
          processors:
          # - add_cloud_metadata: null
          - add_kubernetes_metadata:
              default_matchers.enabled: false
              in_cluster: true
              matchers:
              - logs_path:
                  logs_path: /var/log/containers/
          - drop_fields:
              fields: ["agent.ephemeral_id", "agent.id", "agent.name", "agent.type", "agent.version", "container.id", "container.runtime", "ecs.version", "host.name", "input.type", "/kubernetes.labels.*/", "/kubernetes.namespace_labels.*/", "kubernetes.namespace_uid", "kubernetes.node.name", "kubernetes.node.uid", "/kubernetes.node.labels.*/"]
              ignore_missing: false
          - drop_event.when.or:
            - equals.kubernetes.namespace: bakery
            - equals.kubernetes.namespace: "c-istio-*"
            - equals.kubernetes.namespace: "istio-*"
            - equals.kubernetes.namespace: tools
            - equals.kubernetes.namespace: c-logging
            - equals.kubernetes.namespace: c-monitoring
            - equals.kubernetes.namespace: calico-system
            - equals.kubernetes.namespace: tigera-operator
            - regexp.kubernetes.namespace: "^openshift*"
            - regexp.kubernetes.namespace: "^ibm-*"
            - regexp.kubernetes.namespace: "^d-(.*)"
            - regexp.kubernetes.namespace: "^kube-*"
            - regexp.kubernetes.namespace: "^group-sync-*"
      modules:
        - module: system
          syslog:
            enabled: true
          auth:
            enabled: true
      # Section Autodiscover
      filebeat.autodiscover.providers:
        providers:
        - type: kubernetes
          host: ${NODE_NAME}
          templates:
          - config:
              - type: container
                paths:
                  - /var/log/containers/*-${data.kubernetes.container.id}.log
                exclude_lines: ["^\\s+[\\-`('.|_]"]  # drop asciiart lines
#         node: ${NODE_NAME}
#          hints:
#            enabled: true
#            default_config:
#              type: container
#              paths:
#              - /var/log/containers/*.log
#              - /var/log/containers/*${data.kubernetes.container.id}.log
    # processors:
    # - add_cloud_metadata: null
    # - add_host_metadata: {}
    # ----------------- #
    # Configure Output:
    # https://www.elastic.co/guide/en/beats/filebeat/current/logstash-output.html
    # ----------------- #

    output.elasticsearch:
      enabled: false
    output.logstash:
      enabled: true
      # example: filebeat-8.17.0-2020-10-27
      #index: "%{[@metadata][beat]}-%{[@metadata][version]}-%{+YYYY.MM.dd}"
      index: "filebeat-8.17.0-%{+YYYY.MM.dd}"
      hosts: ["c-logging-logstash.c-logging.svc:5044"]
    setup.dashboards.enabled: false
    setup.kibana.host: ""

  daemonSet:
    podTemplate:
      spec:
        tolerations:
        - key: infra
          operator: Exists
          effect: NoSchedule
        - key: infra
          operator: Exists
          effect: NoExecute
        - key: node-role.kubernetes.io/infra
          operator: Exists
          effect: NoSchedule
        - key: node.ocs.openshift.io/storage
          operator: Exists
          effect: NoSchedule
        # - effect: NoSchedule
        #   operator: Exists
        # nodeSelector:
        #   kubernetes.io/os: linux
        serviceAccountName: c-logging-filebeat
        automountServiceAccountToken: true
        terminationGracePeriodSeconds: 30
        dnsPolicy: ClusterFirstWithHostNet
        hostNetwork: false # Allows to provide richer host metadata
        containers:
        # ------------------ #
        # Filebeat Exporter
        # ------------------ #
        - name: beats-exporter
          image: "{{ imageInstanceLocation }}/{{ beatExporterImageName }}:{{ beatExporterImageTag }}"
          imagePullPolicy: IfNotPresent
          args:
            - -p=5066
            - -l=error
            - -f=filebeat_info
            - -f=uptime
            - -f=handles
            - -f=output
            - -f=filebeat{events
            - -f=pipeline{
            - -f=filebeat_beat
            - -f=filebeat_libbeat
            - -f=registrar{
            - -f=filebeat_system
            - -f=filebeat_filebeat_harvester_open_files
            - -f=filebeat_filebeat_harvester_running
            - -f=filebeat_filebeat_harvester_skipped
            - -f=filebeat_filebeat_harvester_started
            - -f=filebeat_filebeat_harvester_closed
          securityContext:
            runAsUser: 1000
          resources:
            limits:
              cpu: 100m
              memory: 32Mi
            requests:
              cpu: 50m
              memory: 32Mi
          ports:
            - containerPort: 8080
              name: metrics
        # ------------------ #
        # Filebeat Container
        # ------------------ #
        - name: filebeat
          securityContext:
            runAsUser: 0
            # Need privileged container with OCP 
            privileged: true
          resources:
            limits:
              cpu: {{ filebeatResourcesCPULimit }}
              memory: {{ filebeatResourcesMemoryLimit }}
            requests:
              cpu: 100m
              memory: 100Mi
          volumeMounts:
          - name: varlogcontainers
            mountPath: /var/log/containers
          - name: varlogpods
            mountPath: /var/log/pods
          - name: varlibdockercontainers
            mountPath: /var/lib/docker/containers
          # ------------------ #
          # Host var/log mount
          # ------------------ #
          - name: varlog
            mountPath: /var/log
          # ------------------ #
          # In case enable filebeat config in /usr/share/filebeat
          # ------------------ #
          # - name: filebeat-config
          #   mountPath: /usr/share/filebeat/filebeat.yml
          #   readOnly: true
          #   subPath: filebeat.yml
            # ---------------------------------------
            # VAR DATA --> mount only in IKS clusters
            # ---------------------------------------
          - name: var-data-kubeletlogs
            mountPath: /var/data/kubeletlogs
            readOnly: true
            # ---------------------------------------
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName

        volumes:
        - name: varlogcontainers
          hostPath:
            path: /var/log/containers
        - name: varlogpods
          hostPath:
            path: /var/log/pods
        - name: varlibdockercontainers
          hostPath:
            path: /var/lib/docker/containers
        # ------------------ #
        # Host var/log mount
        # ------------------ #
        - name: varlog
          hostPath:
            path: /var/log/

        # ---------------------------------------
        # VAR DATA --> mount only in IKS clusters
        # ---------------------------------------
        - name: var-data-kubeletlogs
          hostPath:
            path: /var/data/kubeletlogs
        # ---------------------------------------
        # ------------------ #
        # In case filebeat config in /usr/share/filebeat
        # ------------------ #
        # - name: filebeat-config
        #   secret:
        #     secretName: c-logging-filebeat
