{
 "title": "ISCP - Logstash",
 "description": "Logstash Health Monitoring: System, JVM, Pipeline and individual plugin stats for Logstash replicas running on Kubernetes.",
 "tags": [
  "logstash",
  "telemetry"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "cpu_threshold", "label": "CPU Threshold", "query": "1.0" },
   {
    "name": "pod",
    "label": "Replica",
    "query": {
     "query": "query_result({pod=~'c-logging-logstash.*'})"
    }
   },
   {
    "name": "pipeline",
    "label": "Logstash Pipeline",
    "query": {
     "query": "query_result(logstash_stats_pipeline_events_in{service=~'c-logging-logstash'})"
    }
   },
   {
    "name": "input_plugin",
    "query": {
     "query": "query_result(logstash_stats_pipeline_plugin_events_out{pod=~'$pod',plugin_type='input'})"
    }
   },
   {
    "name": "filter_plugin",
    "query": {
     "query": "query_result(logstash_stats_pipeline_plugin_events_out{pod=~'$pod',plugin_type='filter'})"
    }
   },
   {
    "name": "output_plugin",
    "query": {
     "query": "query_result(logstash_stats_pipeline_plugin_events_out{pod=~'$pod',plugin_type='output'})"
    }
   },
   {
    "name": "plugin_type",
    "label": "Plugin Type",
    "query": {
     "query": "query_result(logstash_stats_pipeline_plugin_events_duration{pod=~'$pod'})"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "About this Dashboard",
   "type": "text",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "options": {
    "content": "# Logstash Metrics\n\nThis presents metrics for Logstash in the Acme NebulaOne Cluster.\n\nThere are three pipelines running:\n\n* `telemetry-legacy`: A telemetry pipleine for legacy-format clients.\n* `telemetry-json`: A telemetry pipeline for upgraded clients.\n* `testing-stdout`: A testing pipeline, outputting only to stdout."
   }
  },
  {
   "title": "Total Events In/Out",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(logstash_stats_pipeline_events_in{pod=~'$pod',pipeline=~'$pipeline'}[$__range]))",
     "legendFormat": "IN"
    },
    {
     "expr": "sum(increase(logstash_stats_pipeline_events_out{pod=~'$pod',pipeline=~'$pipeline'}[$__range]))",
     "legendFormat": "OUT"
    }
   ]
  },
  { "title": "Status Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Deployed Chart Version by Replica",
   "type": "stat",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "prefix: v" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(logstash_info_status) by (pod, version, status)"
    }
   ]
  },
  {
   "title": "Output Write Successes",
   "type": "stat",
   "description": "Successful Writes to Elasticsearch/OpenSearch",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "Ok" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (pipeline, plugin, plugin_id) (logstash_stats_pipeline_plugin_documents_successes{plugin!=\"stdout\"})",
     "legendFormat": "{{pipeline}} -> {{plugin}}"
    }
   ]
  },
  {
   "title": "Pipeline Status + Max Rate Last Hour",
   "type": "stat",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(rate(logstash_stats_pipeline_events_out{pod=~'$pod',pipeline=~\"$pipeline\"}[$__range]) / rate(logstash_stats_pipeline_events_duration{pod=~'$pod',pipeline=~\"$pipeline\"}[$__range])*1000 > 0) by (pipeline) or max(logstash_stats_pipeline_up{}) by (pipeline)",
     "legendFormat": "{{rate}}"
    }
   ]
  },
  {
   "title": "Output Write Failures",
   "type": "stat",
   "description": "Failed Writes to Elasticsearch/OpenSearch",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "Failed" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (pipeline, plugin, plugin_id) (logstash_stats_pipeline_plugin_documents_non_retryable_failures{plugin!=\"stdout\"})",
     "legendFormat": "{{pipeline}} -> {{plugin}}"
    }
   ]
  },
  {
   "title": "System Load Averages by Replica",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 }
  },
  {
   "title": "System Load Average ($pod)",
   "type": "timeseries",
   "description": "Processes using or waiting for CPU",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 20 },
   "repeat": "pod",
   "targets": [
    {
     "expr": "logstash_stats_process_cpu_load_average_1m{pod=~'$pod'}",
     "legendFormat": "1 min"
    },
    {
     "expr": "logstash_stats_process_cpu_load_average_5m{pod=~'$pod'}",
     "legendFormat": "5 min"
    },
    {
     "expr": "logstash_stats_process_cpu_load_average_15m{pod=~'$pod'}",
     "legendFormat": "15 min"
    },
    { "expr": "$cpu_threshold", "legendFormat": "threshold1" }
   ]
  },
  {
   "title": "Process Metrics (All Selected Replicas)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 }
  },
  {
   "title": "CPU Utilization %",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "logstash_stats_process_cpu_percent{pod=~'$pod'}",
     "legendFormat": "cpu_pct ({{pod}})"
    }
   ]
  },
  {
   "title": "Logstash Process Total Virtual Memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 8, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "logstash_stats_process_mem_total_virtual{pod=~'$pod'}",
     "legendFormat": "vmem ({{pod}})"
    }
   ]
  },
  {
   "title": "Logstash FIle Descriptors",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "logstash_stats_process_max_file_descriptors{pod=~'$pod'}",
     "legendFormat": "max_fds ({{pod}})"
    },
    {
     "expr": "logstash_stats_process_open_file_descriptors{pod=~'$pod'}",
     "legendFormat": "open_fds ({{pod}})"
    }
   ]
  },
  { "title": "JVM  (All Selected Replicas)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Old pool usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "logstash_stats_jvm_mem_pool_committed_bytes{pool='old',pod=~'$pod'}",
     "legendFormat": "old_pool_committed ({{pod}})"
    },
    {
     "expr": "logstash_stats_jvm_mem_pool_max_bytes{pool='old',pod=~'$pod'}",
     "legendFormat": "old_pool_max ({{pod}})"
    },
    {
     "expr": "logstash_stats_jvm_mem_pool_peak_max_bytes{pool='old',pod=~'$pod'}",
     "legendFormat": "old_pool_peak_max ({{pod}})"
    },
    {
     "expr": "logstash_stats_jvm_mem_pool_peak_used_bytes{pool='old',pod=~'$pod'}",
     "legendFormat": "old_pool_peak_used ({{pod}})"
    },
    {
     "expr": "logstash_stats_jvm_mem_pool_peak_used_bytes{pool='old',pod=~'$pod'}",
     "legendFormat": "old_used ({{pod}})"
    }
   ]
  },
  {
   "title": "Young pool usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 36 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "logstash_stats_jvm_mem_pool_committed_bytes{pool='young',pod=~'$pod'}",
     "legendFormat": "young_pool_committed ({{pod}})"
    },
    {
     "expr": "logstash_stats_jvm_mem_pool_max_bytes{pool='young',pod=~'$pod'}",
     "legendFormat": "young_pool_max  ({{pod}})"
    },
    {
     "expr": "logstash_stats_jvm_mem_pool_peak_max_bytes{pool='young',pod=~'$pod'}",
     "legendFormat": "young_pool_peak  ({{pod}})"
    },
    {
     "expr": "logstash_stats_jvm_mem_pool_peak_used_bytes{pool='young',pod=~'$pod'}",
     "legendFormat": "young_pool_peak_used ({{pod}})"
    },
    {
     "expr": "logstash_stats_jvm_mem_pool_peak_used_bytes{pool='young',pod=~'$pod'}",
     "legendFormat": "young_used ({{pod}})"
    }
   ]
  },
  {
   "title": "Survivor pool usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 36 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "logstash_stats_jvm_mem_pool_committed_bytes{pool='survivor',pod=~'$pod'}",
     "legendFormat": "{{pod}}-survivor_pool_committed"
    },
    {
     "expr": "logstash_stats_jvm_mem_pool_max_bytes{pool='survivor',pod=~'$pod'}",
     "legendFormat": "{{pod}}-survivor_pool_max"
    },
    {
     "expr": "logstash_stats_jvm_mem_pool_peak_max_bytes{pool='survivor',pod=~'$pod'}",
     "legendFormat": "{{pod}}-survivor_pool_peak_max"
    },
    {
     "expr": "logstash_stats_jvm_mem_pool_peak_used_bytes{pool='survivor',pod=~'$pod'}",
     "legendFormat": "{{pod}}-survivor_pool_peak_used"
    },
    {
     "expr": "logstash_stats_jvm_mem_pool_peak_used_bytes{pool='survivor',pod=~'$pod'}",
     "legendFormat": "{{pod}}-survivor_used"
    }
   ]
  },
  {
   "title": "JVM Heap % used",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "logstash_stats_jvm_mem_heap_used_percent{pod=~'$pod'}",
     "legendFormat": "{{pod}}-jvm-usage"
    }
   ]
  },
  {
   "title": "JVM Heap usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 42 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "logstash_stats_jvm_mem_heap_max_bytes{pod=~'$pod'}",
     "legendFormat": "{{pod}}-jvm-max"
    },
    {
     "expr": "logstash_stats_jvm_mem_heap_used_bytes{pod=~'$pod'}",
     "legendFormat": "{{pod}}-jvm-used"
    }
   ]
  },
  {
   "title": "Threads count",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "logstash_stats_jvm_threads_count{pod=~'$pod'}",
     "legendFormat": "{{pod}}-threads_count"
    },
    {
     "expr": "logstash_stats_jvm_threads_peak_count{pod=~'$pod'}",
     "legendFormat": "{{pod}}-threads_peak"
    }
   ]
  },
  { "title": "Pipeline", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 } },
  {
   "title": "$pod - Events processing times",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 50 },
   "repeat": "pod",
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(irate(logstash_stats_pipeline_events_queue_push_duration{pod=~'$pod'}[$__range])/irate(logstash_stats_pipeline_events_in{pod=~'$pod'}[$__range])) by (pod, pipeline)",
     "legendFormat": "avg waiting time ({{pipeline}})"
    },
    {
     "expr": "avg(irate(logstash_stats_pipeline_events_duration{pod=~'$pod'}[$__range])/irate(logstash_stats_pipeline_events_out{pod=~'$pod'}[$__range])) by (pod, pipeline)",
     "legendFormat": "avg process time  ({{pipeline}})"
    }
   ]
  },
  {
   "title": "Pipeline Queue Size ($pipeline)",
   "type": "timeseries",
   "description": "Documents in Queue",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 56 },
   "repeat": "pod",
   "targets": [
    {
     "expr": "logstash_stats_pipeline_queue_events_count{pod=~\"$pod\",pipeline=~\"$pipeline\"}",
     "legendFormat": "documents in queue"
    }
   ]
  },
  { "title": "Pipeline Inputs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 63 } },
  {
   "title": "Pipeline Input events / sec over the last hour ($pod)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 64 },
   "repeat": "pod",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(logstash_stats_pipeline_events_in{pod=~'$pod'}[$__range])",
     "legendFormat": "{{pipeline}}"
    },
    {
     "expr": "sum by (job) (irate(logstash_stats_pipeline_events_in{pod=~'$pod'}[$__range]))",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Input plugins: Queue Push Waiting Times ($pod)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 71 },
   "repeat": "pod",
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "max(increase(logstash_stats_pipeline_plugin_events_queue_push_duration{pod=~'$pod',pipeline=~\"$pipeline\",plugin=~'$input_plugin',plugin_type='input'}[$__range])*1000/increase(logstash_stats_pipeline_plugin_events_out{pod=~'$pod',pipeline=~\"$pipeline\",plugin=~'$input_plugin',plugin_type='input'}[$__range])) by (pod, pipeline, plugin)",
     "legendFormat": "queue wait: ({{pipeline}}::{{plugin}})"
    }
   ]
  },
  { "title": "Pipeline Outputs ($pipeline)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 78 }, "repeat": "pipeline" },
  {
   "title": "Output events ($pod) ($output_plugin)",
   "type": "timeseries",
   "description": "An \"output event\" is a 20MB \"bulk\" send in most cases",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 79 },
   "repeat": "pod",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(logstash_stats_pipeline_plugin_events_out{pod=~'$pod',pipeline=~\"$pipeline\",plugin=~'$output_plugin',plugin_type='output'}[$__range])",
     "legendFormat": "{{pipeline}} ({{plugin}})"
    }
   ]
  },
  {
   "title": "Pipeline Output events / sec over the last hour ($pod)",
   "type": "timeseries",
   "description": "An \"output event\" is a 20MB \"bulk\" send in most cases",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 85 },
   "repeat": "pod",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(logstash_stats_pipeline_plugin_events_out{pod=~'$pod',plugin_type='output'}[$__range])",
     "legendFormat": "{{replica}} {{pipeline}}"
    },
    {
     "expr": "sum by (job) (irate(logstash_stats_pipeline_plugin_events_out{pod=~'$pod',plugin_type='output'}[$__range]))",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Pipeline I/O Health ($pipeline)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 120 },
   "repeat": "pipeline"
  },
  {
   "title": "Processed Events I/O Rate ($pod)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 121 },
   "repeat": "pod",
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "avg((irate(logstash_stats_pipeline_events_out{pod=~'$pod',pipeline=~\"$pipeline\"}[$__range])/irate(logstash_stats_pipeline_events_duration{pod=~'$pod',pipeline=~\"$pipeline\"}[$__range]))*1000) by (pod, pipeline)",
     "legendFormat": "Overall Rate (events/sec)"
    },
    {
     "expr": "avg((irate(logstash_stats_pipeline_queue_events_count{pod=~'$pod',pipeline=~\"$pipeline\",plugin_type='input'}[$__range])/irate(logstash_stats_pipeline_events_queue_push_duration{pod=~'$pod',pipeline=~\"$pipeline\",plugin_type='input'}[$__range]))*1000) by (pod, pipeline)",
     "legendFormat": "Input Queue Pressure (events/sec)"
    },
    {
     "expr": "avg((irate(logstash_stats_pipeline_plugin_events_out{pod=~'$pod',pipeline=~\"$pipeline\",plugin_type='output'}[$__range])/irate(logstash_stats_pipeline_plugin_events_duration{pod=~'$pod',pipeline=~\"$pipeline\",plugin_type='output'}[$__range])*1000) < 100000) by (pod, pipeline)",
     "legendFormat": "Outputs Rate (events/sec)"
    }
   ]
  },
  { "title": "Pipeline Filters ($pipeline)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 141 }, "repeat": "pipeline" },
  {
   "title": "Processing Rate for Filters used in Pipeline $pipeline::$filter_plugin ($pod)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 142 },
   "repeat": "pod",
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(logstash_stats_pipeline_plugin_events_in{pod=\"$pod\",pipeline=~\"$pipeline\",plugin=~\"$filter_plugin\",plugin_type='filter'}[$__range])/increase(logstash_stats_pipeline_plugin_events_duration{pod=\"$pod\",pipeline=~\"$pipeline\",plugin=~\"$filter_plugin\",plugin_type='filter'}[$__range])*1000) by (plugin, plugin_id)",
     "legendFormat": "{{plugin}} ({{plugin_id}})"
    }
   ]
  }
 ]
}