---
kind: Service
apiVersion: v1
metadata:
  name: c-logging-elasticsearch-metrics
  namespace: c-logging
  labels:
    k8s-app: c-logging-elasticsearch-exporter
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 9108
      protocol: TCP
  selector:
    k8s-app: c-logging-elasticsearch-exporter
