---
# Source: logstash/templates/pipeline-config.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: c-logging-logstash-pipeline
  namespace: c-logging
  labels:
    app: logstash
    chart: logstash-2.4.0
    release: c-logging-logstash
    heritage: Helm
data:
  input_main.conf: |-
    input {
      # udp {
      #   port => 1514
      #   type => syslog
      # }
      # tcp {
      #   port => 1514
      #   type => syslog
      # }
      beats {
        port => 5044
      }
      # http {
      #   port => 8080
      # }
      # kafka {
      #   ## ref: https://www.elastic.co/guide/en/logstash/current/plugins-inputs-kafka.html
      #   bootstrap_servers => "kafka-input:9092"
      #   codec => json { charset => "UTF-8" }
      #   consumer_threads => 1
      #   topics => ["source"]
      #   type => "example"
      # }
    }
  filter_main.conf: |-
    filter {
      # drop empty lines
      if [message] =~ /^\s*$/ {
        drop { }
      }
      else {
        # remove beats_input_codec_plain_applied tag if exists
        if "beats_input_codec_plain_applied" in [tags] {
          mutate {
            remove_tag => ["beats_input_codec_plain_applied"]
          }
        }
        # remove raw event tag
        if "beats_input_raw_event" in [tags] {
          mutate {
            remove_tag => ["beats_input_raw_event"]
          }
        }
        # drop namespaceless events
        if ![kubernetes][namespace] {
          drop { }
        }
      }
      mutate {
         remove_field => [ "[event][original]" ]
      }
    }
  output_main.conf: |-
    # # debug part for logstash dev use only
    # output {
    #     stdout { codec => rubydebug }
    # }
    # # Comment all above to test the debug part
    output {
      elasticsearch {
        hosts => ["${ELASTICSEARCH_HOST}:${ELASTICSEARCH_PORT:9200}"]
        index => "%{[kubernetes][namespace]}-%{+YYYY.MM.dd}"
        user => elastic
        password => "${ELASTICSEARCH_PASSWORD}"
        # If TLS connection is needed, set ssl variable to true
        ssl => false
        ssl_certificate_verification => false
        cacert => "/usr/share/logstash/ca.crt"
        manage_template => false
        data_stream => false
      }
      # # x-siem send event logs of MT to MF
      # syslog {
      #   host => "{{ SiemHost }}"
      #   port => {{ SiemPort }}
      #   protocol => "tcp"
      #   rfc => "rfc5424"
      #   id => "logstash_syslog"
      #   appname => "{{ clusterName }}_c-logging"
      # }
    }
