### Custom clusterrole to create temporal token
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: c-logging-kibana
rules:
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
