---
apiVersion: batch/v1
kind: Job
metadata:
  name: c-logging-es-backup-repo
  namespace: c-logging
  labels:
    k8s-app: c-logging-elasticsearch
    app.kubernetes.io/managed-by: iscp
    app.kubernetes.io/app-name: application_logging
    app.kubernetes.io/app-catalog: simple
    app.kubernetes.io/app-sla: 24x7
    app.kubernetes.io/app-management: application
    app.kubernetes.io/component: elasticsearch
    app.kubernetes.io/version: 8.8.2
spec:
  completions: 1
  parallelism: 1
  template:
    metadata:
      labels:
        k8s-app: c-logging-elasticsearch
    spec:
      securityContext:
        runAsUser: 1000
      serviceAccount: c-logging-elasticsearch
      containers:
      - name: c-logging-elasticsearch-backup-repo
        image: "docker.elastic.co/elasticsearch/elasticsearch:8.12.2"
        imagePullPolicy: IfNotPresent
        command:
        - /bin/bash
        args:
        - -c
        - |
          while ! curl -X GET "$ELASTICSEARCH_PROTOCOL://$ELASTICSEARCH_HOST:$ELASTICSEARCH_PORT/_cluster/health?wait_for_status=green&timeout=10s&pretty" \
                       -s -o /dev/null -k -u "elastic:$ELASTICSEARCH_PASSWORD"; do
            echo "Waiting for the c-logging Elasticsearch to be green..."
            sleep 30
          done
          rc=""
          echo "Setting up the snapshot repository..."
          while [ "$rc" != "200" ]; do
              rc=`curl -X PUT "$ELASTICSEARCH_PROTOCOL://$ELASTICSEARCH_HOST:$ELASTICSEARCH_PORT/_snapshot/$SNAPSHOT_REPO_NAME?pretty" \
                   -k -u "elastic:$ELASTICSEARCH_PASSWORD" \
                   -H'Content-Type: application/json' \
                   -d '{"type": "fs","settings": {"location": "/usr/share/elasticsearch/backup","compress": true}}' \
                   -s -o /dev/null -w %{http_code}`
              sleep 10
          done
          echo "Done"
        env:
        - name: ELASTICSEARCH_PROTOCOL
          value: "http"
        - name: ELASTICSEARCH_HOST
          value: "c-logging-elasticsearch-es-http.c-logging"
        - name: ELASTICSEARCH_PORT
          value: "9200"
        - name: ELASTICSEARCH_PASSWORD
          valueFrom:
            secretKeyRef:
              key: elastic
              name: c-logging-elasticsearch-es-elastic-user
        - name: SNAPSHOT_REPO_NAME
          value: "{{ snapshotRepoName }}"
        - name: SNAPSHOT_SCHEDULE
          value: "{{ snapshotSchedule }}"
        - name: SNAPSHOT_RETENTION
          value: "{{ snapshotRetention }}"
        - name: ES_JAVA_OPTS
          value: "-Dlog4j2.formatMsgNoLookups=true"
        resources:
          limits:
            cpu: 400m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 56Mi
      restartPolicy: OnFailure
