---
apiVersion: v1
kind: Service
metadata:
  name: c-logging-webhook-server
  namespace: c-logging
spec:
  ports:
    - port: 443
      targetPort: 9443
  selector:
    control-plane: c-logging-operator
