# Source: eck-operator/templates/webhook.yaml
apiVersion: v1
kind: Secret
metadata:
  name: elastic-webhook-server-cert
  namespace: c-logging
  labels:
    control-plane: c-logging-operator
    app.kubernetes.io/version: "2.16.1"