{
 "title": "ACOC  - Filebeat",
 "description": "Dashboard for Filebeat from Prometheus.",
 "tags": [
  "ACOC",
  "filebeat",
  "elasticsearch"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "instance",
    "label": "instance",
    "query": "label_values(filebeat_info,instance)"
   },
   {
    "name": "namespace",
    "label": "namespace",
    "query": "label_values(filebeat_info,namespace)"
   },
   {
    "name": "version",
    "query": "label_values(filebeat_info, version)"
   },
   {
    "name": "podname",
    "query": "label_values(filebeat_beat_info_uptime_ms, pod)"
   }
  ]
 },
 "panels": [
  { "title": "HOST - System and CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "HOST - CPU CORES",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(filebeat_system_cpu_cores{instance=~\"$instance\"}) /  count(filebeat_system_cpu_cores{instance=~\"$instance\"})"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 6, "x": 4, "y": 1 },
   "content": "---\n---\n**$podname**\n---\n---\n---"
  },
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 6, "x": 10, "y": 1 },
   "content": "---\n---\nFilebeat version: **$version**\n---\n---\n---"
  },
  {
   "title": "Filebeat - Uptime [Single Host]",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 1 },
   "targets": [
    {
     "expr": "filebeat_beat_info_uptime_ms{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "System CPU Load [$interval]",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(filebeat_system_load_1{instance=~\"$instance\"}[$interval])",
     "legendFormat": "LOAD 1 - {{instance}}"
    },
    {
     "expr": "rate(filebeat_system_load_5{instance=~\"$instance\"}[$interval])",
     "legendFormat": "LOAD 5 - {{instance}}"
    },
    {
     "expr": "rate(filebeat_system_load_15{instance=~\"$instance\"}[$interval])",
     "legendFormat": "LOAD 15 - {{instance}}"
    }
   ]
  },
  {
   "title": "System CPU Load Norm [$interval]",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(filebeat_system_load{instance=~\"$instance\",norm=\"1\"}[$interval])",
     "legendFormat": "NORM 1 - {{instance}}"
    },
    {
     "expr": "rate(filebeat_system_load{instance=~\"$instance\",norm=\"5\"}[$interval])",
     "legendFormat": "NORM 5 -{{instance}}"
    },
    {
     "expr": "rate(filebeat_system_load{instance=~\"$instance\",norm=\"15\"}[$interval])",
     "legendFormat": "NORM 15 - {{instance}}"
    }
   ]
  },
  {
   "title": "CPU Ticks [$interval]",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(filebeat_beat_cpu_total_ticks{instance=~\"$instance\"}[$interval])",
     "legendFormat": "{{instance}} TICKS"
    }
   ]
  },
  {
   "title": "CPU Time Milliseconds [$interval]",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "rate(filebeat_beat_cpu_user_time_ms[$interval])",
     "legendFormat": "{{instance}} CPU USER TME"
    }
   ]
  },
  { "title": "Filebeat", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Libbeat Config Reloads [$interval]",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "rate(filebeat_libbeat_config_reloads{instance=~\"$instance\"}[$interval])"
    }
   ]
  },
  {
   "title": "Events [$interval]",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 4, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(filebeat_filebeat{instance=~\"$instance\",events=\"active\"}[$interval])",
     "legendFormat": "{{instance}} ACTIVE"
    },
    {
     "expr": "rate(filebeat_filebeat{instance=~\"$instance\",events=\"added\"}[$interval])",
     "legendFormat": "{{instance}} ADDED"
    },
    {
     "expr": "rate(filebeat_filebeat{instance=~\"$instance\",events=\"done\"}[$interval])",
     "legendFormat": "{{instance}} DONE"
    }
   ]
  },
  {
   "title": "Harvester [$interval]",
   "type": "graph",
   "gridPos": { "h": 9, "w": 11, "x": 13, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(filebeat_filebeat_harvester_open_files{instance=~\"$instance\"}[$interval])",
     "legendFormat": "{{instance}} HARVESTER OPEN FILES"
    },
    {
     "expr": "rate(filebeat_filebeat_harvester_running{instance=~\"$instance\"}[$interval])",
     "legendFormat": "{{instance}} HARVESTER RUNNING"
    },
    {
     "expr": "rate(filebeat_filebeat_harvester_skipped{instance=~\"$instance\"}[$interval])",
     "legendFormat": "{{instance}} HARVESTER SKIPPED"
    },
    {
     "expr": "rate(filebeat_filebeat_harvester_started{instance=~\"$instance\"}[$interval])",
     "legendFormat": "{{instance}} HARVESTER STARTED"
    }
   ]
  },
  { "title": "Libbeat", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Libbeat Output Events [$interval]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(filebeat_libbeat_output{instance=~\"$instance\",events=\"acked\"}[$interval])",
     "legendFormat": "{{instance}} ACKED"
    },
    {
     "expr": "rate(filebeat_libbeat_output{instance=~\"$instance\",events=\"active\"}[$interval])",
     "legendFormat": "{{instance}} ACTIVE"
    },
    {
     "expr": "rate(filebeat_libbeat_output{instance=~\"$instance\",events=\"batches\"}[$interval])",
     "legendFormat": "{{instance}} BATCHES"
    },
    {
     "expr": "rate(filebeat_libbeat_output{instance=~\"$instance\",events=\"dropped\"}[$interval])",
     "legendFormat": "{{instance}} DROPPED"
    },
    {
     "expr": "rate(filebeat_libbeat_output{instance=~\"$instance\",events=\"duplicates\"}[$interval])",
     "legendFormat": "{{instance}} DUPLICATES"
    },
    {
     "expr": "rate(filebeat_libbeat_output{instance=~\"$instance\",events=\"failed\"}[$interval])",
     "legendFormat": "{{instance}} FAILED"
    },
    {
     "expr": "rate(filebeat_libbeat_output{instance=~\"$instance\",events=\"toomany\"}[$interval])",
     "legendFormat": "{{instance}} TOO MANY"
    },
    {
     "expr": "rate(filebeat_libbeat_output{instance=~\"$instance\",events=\"total\"}[$interval])",
     "legendFormat": "{{instance}} TOTAL"
    }
   ]
  },
  {
   "title": "Libbeat Output Read Bytes + Errors [$interval]",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(filebeat_libbeat_output{instance=~\"$instance\", read=\"bytes\"}[$interval])",
     "legendFormat": "{{instance}} READ BYTES"
    },
    {
     "expr": "rate(filebeat_libbeat_output{instance=~\"$instance\", read=\"errors\"}[$interval])",
     "legendFormat": "{{instance}} READ ERRORS"
    }
   ]
  },
  {
   "title": "Libbeat Output Write Bytes + Errors [$interval]",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 43 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(filebeat_libbeat_output{instance=~\"$instance\", write=\"bytes\"}[$interval])",
     "legendFormat": "{{instance}} WRITE BYTES"
    },
    {
     "expr": "rate(filebeat_libbeat_output{instance=~\"$instance\", write=\"errors\"}[$interval])",
     "legendFormat": "{{instance}} WRITE ERRORS"
    }
   ]
  },
  {
   "title": "Libbeat Pipeline Clients",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 52 },
   "targets": [
    {
     "expr": "filebeat_libbeat_pipeline_clients{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Libbeat Pipeline Events [$interval]",
   "type": "graph",
   "gridPos": { "h": 9, "w": 20, "x": 4, "y": 52 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(filebeat_libbeat_pipeline{instance=~\"$instance\",events=\"active\"}[$interval])",
     "legendFormat": "{{instance}} ACTIVE EVENTS"
    },
    {
     "expr": "rate(filebeat_libbeat_pipeline{instance=~\"$instance\",events=\"dropped\"}[$interval])",
     "legendFormat": "{{instance}} DROPPED EVENTS"
    },
    {
     "expr": "rate(filebeat_libbeat_pipeline{instance=~\"$instance\",events=\"failed\"}[$interval])",
     "legendFormat": "{{instance}} FAILED EVENTS"
    },
    {
     "expr": "rate(filebeat_libbeat_pipeline{instance=~\"$instance\",events=\"filtered\"}[$interval])",
     "legendFormat": "{{instance}} FILTERED EVENTS"
    },
    {
     "expr": "rate(filebeat_libbeat_pipeline{instance=~\"$instance\",events=\"published\"}[$interval])",
     "legendFormat": "{{instance}} PUBLISHED EVENTS"
    },
    {
     "expr": "rate(filebeat_libbeat_pipeline{instance=~\"$instance\",events=\"retry\"}[$interval])",
     "legendFormat": "{{instance}} RETRY EVENTS"
    },
    {
     "expr": "rate(filebeat_libbeat_pipeline{instance=~\"$instance\",events=\"total\"}[$interval])",
     "legendFormat": "{{instance}} TOTAL EVENTS"
    }
   ]
  },
  {
   "title": "Libbeat Pipeline Queue ACKED [$interval]",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 56 },
   "targets": [
    {
     "expr": "rate(filebeat_libbeat_pipeline_queue_acked{instance=~\"$instance\"}[$interval])"
    }
   ]
  },
  { "title": "Memstats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 61 } },
  {
   "title": "Memstats GC Next [$interval]",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 62 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(filebeat_beat{instance=~\"$instance\",memstats=\"gc_next\"}[$interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memstats Memory Alloc [$interval]",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 62 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(filebeat_beat{instance=~\"$instance\",memstats=\"memory_alloc\"}[$interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memstats Memory Total [$interval]",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 71 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(filebeat_beat{instance=~\"$instance\",memstats=\"memory_total\"}[$interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memstats RSS [$interval]",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 71 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(filebeat_beat{instance=~\"$instance\",memstats=\"rss\"}[$interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Registrar", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 80 } },
  {
   "title": "Registrar Stats [$interval]",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 81 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(filebeat_registrar{instance=~\"$instance\",states=\"cleanup\"}[$interval])",
     "legendFormat": "{{instance}} CLEANUP"
    },
    {
     "expr": "rate(filebeat_registrar{instance=~\"$instance\",states=\"current\"}[$interval])",
     "legendFormat": "{{instance}} CURRENT"
    },
    {
     "expr": "rate(filebeat_registrar{instance=~\"$instance\",states=\"update\"}[$interval])",
     "legendFormat": "{{instance}} UPDATE"
    }
   ]
  },
  {
   "title": "Registrar Writes [$interval]",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 81 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(filebeat_registrar{instance=~\"$instance\",writes=\"fail\"}[$interval])",
     "legendFormat": "{{instance}} FAIL"
    },
    {
     "expr": "rate(filebeat_registrar{instance=~\"$instance\",writes=\"success\"}[$interval])",
     "legendFormat": "{{instance}} SUCCESS"
    },
    {
     "expr": "rate(filebeat_registrar{instance=~\"$instance\",writes=\"total\"}[$interval])",
     "legendFormat": "{{instance}} TOTAL"
    }
   ]
  }
 ]
}