---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: c-logging-ilm-slm-privileged
  namespace: c-logging
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:privileged
subjects:
- kind: ServiceAccount
  name: c-logging-ilm-slm
  namespace: c-logging